apiVersion: v1
kind: PersistentVolume
metadata:
  name: zeek-nfs
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  storageClassName: zeek-nfs
  nfs:
    server: 172.18.109.9
    path: "/var/tmp/Kubernetes/nfs"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zeek-nfs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: zeek-nfs  # Make sure it matches the PV's storageClassName
  resources:
    requests:
      storage: 200Mi  # Corrected to use lowercase "i"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeek-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zeek
  template:
    metadata:
      labels:
        app: zeek
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 300
        - key: "node.kubernetes.io/memory-pressure"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 300
      containers:
        - name: zeek
          image: zeek/zeek:latest
          command: ["zeek", "-i", "eth0"]
          volumeMounts:
            - name: zeek-logs
              mountPath: /usr/local/zeek/logs
      volumes:
        - name: zeek-logs
          persistentVolumeClaim:
            claimName: zeek-nfs-claim

---
apiVersion: v1
kind: Service
metadata:
  name: zeek-service
spec:
  selector:
    app: zeek
  ports:
    - protocol: TCP
      port: 47760
      targetPort: 47760
  type: LoadBalancer

