AWSTemplateFormatVersion: '2010-09-09'
Description: Python Architecture - VPC-2.0
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro # Adjust instance type as needed
      ImageId: ami-04a81a99f5ec58529 # Specify your desired AMI ID
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup # Reference to security group allowing ports 22 and 80
      NetworkInterfaces:
        - AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          GroupSet:
            - !Ref InstanceSecurityGroup # Reference to security group allowing ports 22 and 80
      userdata: !Base64
        Fn::Sub: |
          #!/bin/bash
          # Installing requirements
          sudo apt-get update && sudo apt-get install -y python3 python3-venv git python3-dev default-libmysqlclient-dev build-essential pkg-config libmysqlclient-dev
          # Cloning the repository
          git clone https://github.com/Venkatakarthik0211/testrepo.git
          # Navigating to the project directory and setting up the virtual environment
          cd /home/ubuntu/testrepo/three-tier/python/test/ && python3 -m venv venv && source venv/bin/activate
          # Installing Gunicorn and other required packages
          pip3 install gunicorn && pip3 install -r requirements.txt
          # Creating the systemd service file for Gunicorn
          sudo bash -c 'cat <<EOF > /etc/systemd/system/flaskec.service
          [Unit]
          Description=Gunicorn instance for our flask app
          After=network.target
          [Service]
          User=ubuntu
          Group=www-data
          WorkingDirectory=/home/ubuntu/testrepo/three-tier/python/test
          ExecStart=/home/ubuntu/testrepo/three-tier/python/test/venv/bin/gunicorn -b localhost:8000 app:app
          Restart=always
          [Install]
          WantedBy=multi-user.target
          EOF'
          # Reloading the systemd daemon to include the new service, enabling, and starting it
          sudo systemctl daemon-reload && sudo systemctl enable flaskec && sudo systemctl start flaskec && sudo systemctl status flaskec
          # Install nginx and start the service
          sudo apt-get install nginx -y && sudo systemctl start nginx && sudo systemctl enable nginx && sudo systemctl status nginx
      Tags:
        - Key: Name
          Value: EC2Instance

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 # Allow SSH from NAT EC2 instance (adjust as needed)
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0 # Allow HTTP from anywhere (adjust as needed)
      Tags:
        - Key: Name
          Value: InstanceSecurityGroup